### ISSUE TITLE
Missing library: libgunicode Error

### ISSUE THREAD

**Issue by Cstrachan4** [linusromer/mf2outline#1]
Hey, 

I'm having some issues running the python script in terminal on Mac osx Mavericks (10.9.5).

I'm rather new to this so maybe I'm going wrong somewhere, but it seems that font-forges python extension has not installed properly?

I have tried a few different versions from here https://fontforge.github.io/en-US/downloads/mac/ as well as using this installer https://github.com/jenius/Fontforge-Installer. 

But when I run the python script from terminal I get the following error:

File "/Users/Callum/Desktop/mf2outline.py", line 23, in <module>
    import os,sys,fontforge,glob,subprocess,tempfile,shutil,argparse,math
SystemError: Missing library: libgunicode

Further info (requirements) – 

Python interpreter – the default version that comes with mavericks (Python 2.7.5) installed at /usr/bin/python

Metapost compiler – Haven't installed individually but have TeXShop installed so assumed it would be installed as part of this?

Any ideas on how to fix this? Should I be installing fontforge via homebrew? If so how do I go about this?

Let me know if any further info is required

Thanks in advance!

**Comment by koffeinfrei** [comment]
Can you try the standalone import in an interactive python session, just to be sure that it's actually the fontforge library that causes the error?

``` shell
$ python
>>> import fontforge;
```

How did you install the python package?

You could alternatively try installing it with [homebrew](http://brew.sh/).

**Comment by Cstrachan4** [comment]
Okay, so I have reinstalled fontforge and the python extension with homebrew via the following

`brew install -v fontforge --enable-pyextension`

and now when I try the standalone import I get a different error message

```
 >>> import fontforge
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
SystemError: No initialization function in fontforge library
```

**Comment by linusromer** [comment]
Sorry, I do not have a Mac and this is not an issue of mf2outline, but rather an issue of fontforge. It may be better to ask the fontforge people for support.
One guess: You might not have installed all the dependencies (listed e.g. on http://braumeister.org/formula/fontforge)

**Comment by Cstrachan4** [comment]
Okay, no worries! Thanks for the help anyway!
