### ISSUE TITLE
MF Bespoke -f mode error 

### ISSUE THREAD

**Issue by MarcoMueller** [linusromer/mf2outline#2]
pen width (px) = 1.4 generates an almost empty font for -f mode:
http://www.metaflop.com/modulator/font/qrSkJewe2j
found by: https://twitter.com/schuyuan/status/725628472220082176

**Comment by koffeinfrei** [comment]
Still happens with the latest version 20160415:

```
(/tmp/metaflop/nwDQXfC5kHCBviCroAFTRg/bespoke/glyphs/acc/ogonek.mf
! This can't happen (token).
ogonek->...2)=0.5(y(SUFFIX2)l+y(SUFFIX2)r)endgroup

ogonek->...R3)*widthcorr((EXPR4),(EXPR5)),(EXPR5))
                                                  endgroup
l.45 pos14(whatever,right,1.15*(angle -dz)-90)
                                              ;
```

**Comment by koffeinfrei** [comment]
Although this may be an issue with the bespoke, @MarcoMueller is already checking...

**Comment by MarcoMueller** [comment]
@koffeinfrei local MF batches ogonek.mf without problems. I corrected and updated ogonek.mf and cedilla.mf on github. Please try new versions.

**Comment by koffeinfrei** [comment]
www.metaflop.com updated. Seems fine now.

**Comment by koffeinfrei** [comment]
@linusromer can this be closed?

**Comment by linusromer** [comment]
@koffeinfrei I think so...
